#!/usr/bin/env ruby

require "udgenerator/version"
require "udgenerator"
require "thor"

module Udgenerator
  #= Udgenerator CLI
  class CLI < Thor
    default_task :update

    option :auto_init, :type => :boolean, :aliases => '-a', :default => true, :desc => 'auto initialization. all zero or empty string, etc ...'
    option :input, :type => :string, :aliases => '-i', :default => true, :required => true,  :desc => 'input file'
    option :output, :type => :string, :aliases => '-o', :default => true, :desc => 'output directory'
    option :file_name, :type => :string, :aliases => '-f', :default => true, :desc => 'output file name'
    desc "generate", "generate storyboard"
    def update
      Core.new.generate(options)
    end

    desc "version", "version"
    def version
      p VERSION
    end
  end
end

Udgenerator::CLI.start(ARGV)
